### ISSUE TITLE
[K at the end of some lines

### ISSUE THREAD

**Issue by derjanb** [iliazeus/vscode-ansi#10]
Finally ANSI support for VSCode. Thank you so much! That saves me the use of ansi2html and using a HTML preview in VSCode.

There is only one minor issue. I see a sequence ```[K``` at the end of colored lines.

Steps to reproduce at Ubuntu 20.04:

Clone this repo, and run the command line below and open `/tmp/1.diff` in VSCode.

```bash
dwdiff -L4 -P -c package.json tsconfig.json > /tmp/1.diff
```

Thank you.

![image](https://user-images.githubusercontent.com/767504/113340708-85595380-932c-11eb-8262-3090f229bbf3.png)

**Comment by derjanb** [comment]
Yes still present in v1.1.4.

![image](https://user-images.githubusercontent.com/767504/221654954-a69ae9c3-a3eb-4f7e-bcd1-5aaf29a36095.png)

**Comment by iliazeus** [comment]
Can you please attach an example as a text file?

**Comment by derjanb** [comment]
Sure: [1.txt](https://github.com/iliazeus/vscode-ansi/files/10853523/1.txt)

**Comment by iliazeus** [comment]
Should be fixed in v1.1.5

**Comment by derjanb** [comment]
It's working fine now. Thanks!
