### ISSUE TITLE
Cannot execute iliazeus.vscode-ansi.showPretty

### ISSUE THREAD

**Issue by isira-adithya** [iliazeus/vscode-ansi#11]
Hi 👋,

I have been using this extension for about 2 months now and it worked well.
Today, I got this error and I tried to troubleshoot and I cannot get it to working.

It displays this message,
`Command 'ANSI Text: Open Preview' resulted in an error (command 'iliazeus.vscode-ansi.showPretty' not found)`
as a notification. I am using this extension to view terminal output with ANSI.

Thanks a lot.

**Comment by iliazeus** [comment]
Hi! Sadly, I wasn't able to reproduce it. Does it still happen with the latest extension version?

**Comment by iliazeus** [comment]
closing as non-reproducible
