### ISSUE TITLE
Automatically open the preview pane

### ISSUE THREAD

**Issue by aminya** [iliazeus/vscode-ansi#15]
Could we have an option that allows automatically opening the preview pane?

**Comment by iliazeus** [comment]
Back when I started this extension, all the ways to do that were very hacky and ugly. I will look into it again, though.

**Comment by iliazeus** [comment]
Sadly, all solutions I could come up with were _very_ hacky. With the way the preview is currently implemented, there seems to be no nice ways to do that.
