### ISSUE TITLE
esc for no reason

### ISSUE THREAD

**Issue by booboojp** [iliazeus/vscode-ansi#18]
Can I use this is log files to show the color in them. All i see is a red esc box. I am using vs code.
![dsdsdsdsdsdsdsdsds](https://user-images.githubusercontent.com/68347504/210911287-535420af-2d62-49cf-a67f-70005e1cf1cb.PNG)

**Comment by iliazeus** [comment]
You need to tell the extension that it is a file with ANSI colors in it by selecting `F1 - Change Language Mode - ANSI text`. This mode is only enabled by default for files with `.ans` and `.ansi` extensions.
