### ISSUE TITLE
Open .ansi showing "esc[36m" characters

### ISSUE THREAD

**Issue by Khaaz** [iliazeus/vscode-ansi#20]
Hello,

This extension is awesome and work great with the `Open Preview` command.
However I would love it to automatically run the `Open Preview` or at least make it easier to run.
I am using `.log`. files but I try to use `.ansi` as it's supposed to automatically parse it with colors. It indeed does it but I still have weird "escape characters" (see screenshot).
![image](https://user-images.githubusercontent.com/32022851/215871252-182e5a21-48a1-4cb2-a998-ad488cd697a8.png)

Would it be possible to:
- Have an option to choose the file extension that will automatically be syntax highlighter (in my case `.log`
- Have the file correctly rendered when opened directly if I use a `.ansi` extension for example?

**Comment by iliazeus** [comment]
> I am using .log. files but I try to use .ansi as it's supposed to automatically parse it with colors. It indeed does it but I still have weird "escape characters" (see screenshot).

This is a limitation that is not possible to currently overcome, at least with the way the extension is currently implemented.

> Have an option to choose the file extension that will automatically be syntax highlighter (in my case .log

This is possible, I will look into it when I have time.

**Comment by iliazeus** [comment]
The problem with visible escape character _in the "Open Preview" mode_ should be resolved in the latest version.

> Have an option to choose the file extension that will automatically be syntax highlighter (in my case .log

You can set this up yourself. In your `.log` file, press `F1 - Change Language Mode - Configure File Association for '.log' - ANSI text`.

**Comment by Khaaz** [comment]
Thank you for your answer, and for resolving this issue. Much appreciated.

For the record:
- What you mentionned about setting up the language mode to ANSI text works great.
- Open preview works great, no escape character or anything, and the top right "open preview button" works great as well. It's great not to have to manually ctrl+shift+p and type the open preview command
- When NOT in preview mode, but with the "auto parsing" view file association: I have the colors but I still have escapes characters.

I understand that this is a limitation we can't get passed by, I just wanted to follow up 👍🏻 
If it's possible somehow to overcome said limitation though it would be awesome as it is the only thing missing in this extension really.

Last thing: I suggest to add the `Change Language Mode` feature in the README as it would help new users. If possible, it could be interesting to have that as an option in the extension itself (so it can be added to workspace for instance) although it's definitely not mandatory. 

Thanks
