### ISSUE TITLE
Is it possible to open the viewer automatically on .ansi files?

### ISSUE THREAD

**Issue by kobygold** [iliazeus/vscode-ansi#22]
Hi,
Is it possible to avoid clicking the preview icon (or keyboard shortcut), and just open automatically the full window viewer (not the side panel) when an .ansi file is being opened? If there will be an option to view it automatically it would be great.

**Comment by iliazeus** [comment]
Sadly, I don't think it would be possible with the way the code is written. See https://github.com/iliazeus/vscode-ansi/issues/7.
