### ISSUE TITLE
support [2K[1G[31m colors 

### ISSUE THREAD

**Issue by antoinerousseau** [iliazeus/vscode-ansi#23]
in GitHub actions:

<img width="373" alt="Capture d’écran 2023-02-24 à 18 30 45" src="https://user-images.githubusercontent.com/160279/221247807-07196733-a322-43f4-b593-c8a2cb27eab9.png">

in VS Code with this extension:

<img width="454" alt="Capture d’écran 2023-02-24 à 18 31 14" src="https://user-images.githubusercontent.com/160279/221247943-71baa968-43c8-410d-8a30-dd131d5e205d.png">

**Comment by iliazeus** [comment]
Can you please attach an example as a text file?

**Comment by antoinerousseau** [comment]
Indeed, this is now fixed in 1.1.4, thanks @iliazeus!

<img width="619" alt="Capture d’écran 2023-02-27 à 11 19 17" src="https://user-images.githubusercontent.com/160279/221537315-1b3fc5ce-8aa4-4611-b60f-8c9d6c66dbcd.png">

**Comment by antoinerousseau** [comment]
test file, fyi: [11_Run make test-e2e-ci.txt](https://github.com/iliazeus/vscode-ansi/files/10838573/11_Run.make.test-e2e-ci.txt)
