### ISSUE TITLE
Not working anymore.

### ISSUE THREAD

**Issue by nuncio-bitis** [iliazeus/vscode-ansi#24]
Something like this isn't working (real escapes replaced with <ESC>):
<ESC>[38;5;226;1mNOW ONLINE!<ESC>[0m

**Comment by iliazeus** [comment]
Can you please attach an example file?

**Comment by dostuffthatmatters** [comment]
> Can you please attach a file with an example of this bug?

Also not working for me. Here is an example that works correctly in the Terminal but not in `.ans`/`.ansi` files (had to convert it to txt for a GitHub upload):

[4-2-bench.2834010.txt](https://github.com/iliazeus/vscode-ansi/files/11582720/4-2-bench.2834010.txt)

**Comment by iliazeus** [comment]
The `38;5` code is for setting foreground color as RGB. It expected three further arguments (`r;g;b`), but you've only given it two. So the extension just ignores the command.
