### ISSUE TITLE
Version for CudaText?

### ISSUE THREAD

**Issue by Alexey-T** [iliazeus/vscode-ansi#33]
Hello Ilia.
Can I ask for a version for my CudaText editor?
API allows this , but it is in Python, sorry.
Can you help?
It will be very useful plugin.

**Comment by iliazeus** [comment]
Hello!
I don't use CudaText, so I have no interest in porting the extension. You can freely use my code as a reference for your own extension though! Or, if you want to, I can do this as a paid project. If you're interested in that, please email me to discuss the price and the details.
