### ISSUE TITLE
Other file extensions

### ISSUE THREAD

**Issue by Tabaie** [iliazeus/vscode-ansi#35]
Is it possible for the extension to process files with extensions other than `.ansi`? I'd like to view my `nohup.out`s with colors by default.

**Comment by iliazeus** [comment]
Yes - to do that, you should associate the `ANSI text` language with that file extension. It can be done temporarily, by executing `F1 - Change Language Mode - ANSI Text`; or permanently, by editing the `Files: Associations` setting, adding an item with the value of `ansi`.

**Comment by iliazeus** [comment]
Relevant VS Code docs: 
- https://code.visualstudio.com/docs/languages/overview#_change-the-language-for-the-selected-file
- https://code.visualstudio.com/docs/languages/overview#_add-a-file-extension-to-a-language
