### ISSUE TITLE
Support modifiers like bold, underline and dim

### ISSUE THREAD

**Issue by jaydenseric** [iliazeus/vscode-ansi#5]
Notice bold and underline is working in the terminal (bottom) but not in the ANSI preview (top):

<img width="443" alt="Screen Shot 2020-12-04 at 10 20 38 pm" src="https://user-images.githubusercontent.com/1754873/101158012-284fd880-367f-11eb-874c-b3151eecbc25.png">

I've been using this extension all day, but had to revert to using the terminal to preview ANSI with bold, underlined or dim content.

I use [`kaleur`](https://www.npmjs.com/package/kleur) to generate the ANSI for most of the text, while the code frame colorization is done via [`@babel/code-frame`](https://www.npmjs.com/package/@babel/code-frame) using [`chalk`](https://www.npmjs.com/package/chalk).

**Comment by jaydenseric** [comment]
Here are examples of the ANSI:

<img width="186" alt="Screen Shot 2020-12-04 at 10 51 40 pm" src="https://user-images.githubusercontent.com/1754873/101160537-533c2b80-3683-11eb-9f31-d0615abd948a.png">

And here are the results in macOS Terminal (VS Code terminal doesn't always display bold correctly):

<img width="112" alt="Screen Shot 2020-12-04 at 10 49 52 pm" src="https://user-images.githubusercontent.com/1754873/101160598-6bac4600-3683-11eb-8b18-18b0ac707f3b.png">

**Comment by iliazeus** [comment]
Resolved by fb5ec8748edbe51ccd1224884acffea9908d6622 and 965343d159cf9fa0258f00ee67f421fa8eee9118.
