### ISSUE TITLE
Preview becomes corrupted if source ANSI is updated

### ISSUE THREAD

**Issue by jaydenseric** [iliazeus/vscode-ansi#6]
I've noticed I have to close the preview and reopen it every time the ANSI being previewed is updated, otherwise it displays with semi scrambled text and formatting.

**Comment by iliazeus** [comment]
In `1.0.5`, I've made some fixes that could resolve this. @jaydenseric, could you please check if the bug is still there? If it still is, I would appreciate some more info on how to reproduce this.

**Comment by jaydenseric** [comment]
Really nice work in the v1.0.5 release! Fantastic. I just played around and the preview seems to update ok; I'll see if it happens again this week while working on more snapshot tests. If it does, we can reopen :)

**Comment by Julien-goupy** [comment]
This issue is still reproducible on my machine with version 1.1.0

My vscode:
Version: 1.52.1
Commit: ea3859d4ba2f3e577a159bc91e3074c5d85c0523
Date: 2020-12-16T16:32:10.090Z
Electron: 9.3.5
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Linux x64 4.15.0-134-generic
