### ISSUE TITLE
Setting for preview mode as default

### ISSUE THREAD

**Issue by lamuertepeluda** [iliazeus/vscode-ansi#7]
Hi there,

very nice work with this extension! 😃 

I was wondering if it'd be possible to have a setting for which the content is displayed by default as in the current "preview mode", turning the preview into "raw mode" with all the ugly ansi escape codes.

This means adding the possibility to reverse the current behavior.

What do you think about?

**Comment by iliazeus** [comment]
Sadly, I don't think it is possible.

`vscode-ansi` uses VSCode's built-in text editors in readonly mode (via [`TextDocumentContentProvider`](https://code.visualstudio.com/api/references/vscode-api#TextDocumentContentProvider)) for preview display. The only custom editors allowed to open files "by default" (e.g. by double-click) are [webview-based custom editors](https://code.visualstudio.com/api/extension-guides/custom-editors). But building such an editor means reimplementing all the default functionality from scratch - navigation, searching, line wrap, interaction with other extensions (e.g. spell check).

I am closing this issue, as I am not planning to attempt this big of a task in the foreseeable future. If you find an easier way to do it, PRs are always welcome!

**Comment by lumotroph** [comment]
Oh how I wish this was an option!
