### ISSUE TITLE
Support `[0;m` as end of color code

### ISSUE THREAD

**Issue by daladim** [iliazeus/vscode-ansi#8]
Hi,

Thanks for this extension.
Gitlab (ans maybe others) finish their color sequences by `\x1b[0;m` instead of the `\x1b[0m` you expect.
[Example here](https://storage.googleapis.com/gitlab-gprd-artifacts/a6/80/a68072e80f075e89bc74a300101a9e71e8363bdb542182580162553462480a52/2021_01_20/975618075/1064265542/job.log?response-content-type=text%2Fplain%3B%20charset%3Dutf-8&response-content-disposition=inline&GoogleAccessId=gitlab-object-storage-prd@gitlab-production.iam.gserviceaccount.com&Signature=pAQi%2F%2FDRyTJOB%2Br3PYq6DkECSLlqNCealoLIF9HirZFZMDBp9zv7%2BQ333J9O%0AqH%2FHHB%2BiBERL9J%2B%2BhxfT0dR%2Bu%2BpChZ7xax85AvhhMr9gQAo3rdJPTWuML4sv%0Ac4kduhU2T6k6IB4hn2V7Jp0EbolBLKBGKchjdC3QFFnbb1QrzPvwWqhTa%2BfF%0AZlP0w3YbK5tEX4D20FzL9AIT4Op5L9BM7J%2FedCSQVQpCc70KwIMWp7bnWCaC%0ALwwQkROwVl5SGL0gX54HleiWl90D%2BF9FhAT2i7v1f6SMTQXqPhdmZJQLlQVI%0ArT%2B1Vl%2BBQSg7dGOrz21IJFzLWxSP8AHc3LODjety6A%3D%3D&Expires=1611165839)

My gnome-terminal accepts this syntax, so I guess this is defined in the ANSI standards. Could you support this in vscode-ansi?
(I could not find any `[0m` using `grep` in your code, and I'm not fluent in JavaScript, so I haven't found a way to implement this myself)

Thanks

**Comment by iliazeus** [comment]
Fixed in v1.1.0 by implementing our own ANSI parser. Previously, [`ansicolor`](https://www.npmjs.com/package/ansicolor) was used, which, apparently, does not treat such sequences correctly.
