### ISSUE TITLE
Preview gets out of sync if file is changed on disc

### ISSUE THREAD

**Issue by ChrisJefferson** [iliazeus/vscode-ansi#9]
Firstly, thanks for this package!

Sometimes, if a program replaces the file on disc, then the preview gets "out of sync", I (think) it is using the old file to display, but the new file for highlighting.

Here is some pictures where the second one (hopefully) shows the issue. I kept putting blank lines in, then regenerating the file on disc:

![Picture1](https://user-images.githubusercontent.com/811527/105909469-7fd74880-601f-11eb-8592-1f956535ba17.png)
![Picture2](https://user-images.githubusercontent.com/811527/105909478-806fdf00-601f-11eb-8601-8e6fd50c12bf.png)

**Comment by jaydenseric** [comment]
I sometimes see the same thing, sometimes not.

**Comment by iliazeus** [comment]
@ChrisJefferson was the file just modified, or deleted and then created again?

**Comment by ChrisJefferson** [comment]
Deleted and created again -- I'm running a program which produces a log file. So (guessing a bit maybe) I suspect you if had an open file reference to the old copy, you would still see the old contents?

**Comment by iliazeus** [comment]
Should be fixed in `v1.1.1`.

@ChrisJefferson can you please check if it still happens with the newest version?

**Comment by ChrisJefferson** [comment]
This seems to fix the issue, thanks!
